version: "3.7"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo18@2024
      POSTGRES_DB: postgres
    volumes:
      - odoo_pgdata:/var/lib/postgresql/data
    restart: always

  odoo18:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "10018:8069"
      - "20018:8072"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo18@2024
    restart: always

volumes:
  odoo_pgdata:
